### ISSUE TITLE
Fetch trackers every 5 seconds from client side

### ISSUE THREAD

**Issue by denysdovhan** [denysdovhan/chernivtsi-transport#6]
Fetch trackers and draw their positions on the map.

**Comment by makalkin** [comment]
@denysdovhan trackers are already being fetched and streamed, did you forget to close this or you have something else in mind?

**Comment by denysdovhan** [comment]
They are, but the current implementation is pretty rough. I still have to change it, so I keep it open as a reminder.

P.S: Thanks for your interest!
